# https://taskfile.dev

version: '3'

vars:
  ADDITIONAL_URLS: 
    - https://arduino.esp8266.com/stable/package_esp8266com_index.json
    - https://files.seeedstudio.com/arduino/package_seeeduino_boards_index.json
    - https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json

tasks:
  install:
    cmds:
      - sh ./tools/install.sh
  rebuild_config:
    cmds:
      - arduino-cli config init --dest-dir . --overwrite --aditional-urls {{.ADDITIONAL_URLS.join(',')}}
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
